### ISSUE TITLE
Influx: load_influx.sh works not correctly

### ISSUE THREAD

**Issue by juliaabra** [timescale/tsbs#81]
Hello guys,

after installing the relevant go files for generating data and the influx db, following problem occurs:
In the attached file
![terminal_output](https://user-images.githubusercontent.com/52494925/60590299-f0fb3f00-9d9b-11e9-9c3a-981d1bb688cc.png)
it is seen that statistics of the load performance are not written on the terminal as described in the relevant part of the documentation 
![referenced_description](https://user-images.githubusercontent.com/52494925/60590298-f0fb3f00-9d9b-11e9-9258-b78803695664.png)
If not paying attention to this and executing the file for running the queries, an internal go error occurs
![go_error](https://user-images.githubusercontent.com/52494925/60591306-7b44a280-9d9e-11e9-8236-054f00ffe780.png)

This happens with following .zip-file. The data generation works just fine.
[influx-data.gz](https://github.com/timescale/tsbs/files/3354909/influx-data.gz)

Hope, you can fix it.
Thanks

**Comment by RobAtticus** [comment]
Hi @juliaabra , it did not print to the console because the loading took less than 10s, which is the default reporting interval. It only took 386ms so it just prints out the summary.

As for the second problem, it seems you are passing the generated input file into the `tsbs_run_queries_influx` binary, instead of first generating queries (which are then stored in separate `.tar.gz` files) and passing those in.

**Comment by juliaabra** [comment]
Hello @RobAtticus ,

thank you very much for answering so fast and helping.
That was indeed the problem.
I'm very new to that and didn't really noticed my mistake, sorry.
Now I can confirm: it works fine with influx to those people who want to work with it.
